# Generated by Django 5.2.12 on 2026-03-06 18:36

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='SUCCESS', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FunctionalErrorLog',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('function_or_view', models.CharField(max_length=255)),
                ('input_data', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Functional Error',
                'verbose_name_plural': 'Functional Errors',
                'ordering': ['-created'],
            },
        ),
    ]
