# Generated by Django 5.2.12 on 2026-03-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='functionalerrorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module', 'created'], name='log_activit_module_5b058d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['status', 'created'], name='log_activit_status_1a9c14_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address'], name='log_activit_ip_addr_a290b7_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalerrorlog',
            index=models.Index(fields=['is_resolved', 'created'], name='log_functio_is_reso_b58912_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalerrorlog',
            index=models.Index(fields=['error_type', 'created'], name='log_functio_error_t_4b016f_idx'),
        ),
        migrations.AddIndex(
            model_name='functionalerrorlog',
            index=models.Index(fields=['ip_address'], name='log_functio_ip_addr_5945e1_idx'),
        ),
    ]
