# Generated by Django 5.2.12 on 2026-03-12 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0002_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributioncycle',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_cycles', to='communities.community'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finance.contributioncycle'),
        ),
        migrations.AddField(
            model_name='financialseason',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_seasons', to='communities.community'),
        ),
        migrations.AddField(
            model_name='contributioncycle',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_cycles', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='fine',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='fine',
            name='related_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='finance.contribution'),
        ),
        migrations.AddField(
            model_name='fine',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='finepayment',
            name='fine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.fine'),
        ),
        migrations.AddField(
            model_name='finepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fine_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='loan',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='fine',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='finance.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='guarantor_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loan_applications', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='finance.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_payments', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='communities.community'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.loanproduct'),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='finance.loan'),
        ),
        migrations.AddField(
            model_name='memberfinancesnapshot',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_snapshots', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='memberfinancesnapshot',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_finance_snapshots_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberfinancesnapshot',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_finance_snapshots', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='njangibenefit',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='njangi_benefits', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='njangibenefit',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='njangi_benefits', to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payment', to='communities.membershipapplication'),
        ),
        migrations.AddField(
            model_name='registrationpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['status'], name='finance_con_status_6428eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['paid_at'], name='finance_con_paid_at_41be86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('membership', 'cycle')},
        ),
        migrations.AlterUniqueTogether(
            name='financialseason',
            unique_together={('community', 'season_date')},
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'borrow_date'], name='finance_loa_status_47eb76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanguarantor',
            unique_together={('loan_application', 'guarantor_membership')},
        ),
        migrations.AlterUniqueTogether(
            name='loanproduct',
            unique_together={('community', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='loanrepaymentschedule',
            unique_together={('loan', 'installment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='memberfinancesnapshot',
            unique_together={('membership', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='njangibenefit',
            unique_together={('membership', 'season')},
        ),
    ]
