# Generated by Django 5.2.12 on 2026-03-23 05:47

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communityfeature_feature_type'),
        ('finance', '0003_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='njangibenefit',
            name='cycle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='njangi_benefit', to='finance.contributioncycle'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(choices=[('late_contribution', 'Late Contribution'), ('absence', 'Absence'), ('late_repayment', 'Late Repayment'), ('manual', 'Manual')], max_length=30),
        ),
        migrations.CreateModel(
            name='NjangiRotation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('position', models.PositiveIntegerField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='njangi_rotations', to='communities.membership')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='njangi_rotations', to='finance.financialseason')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('season', 'membership'), ('season', 'position')},
            },
        ),
    ]
