# Generated by Django 5.2.12 on 2026-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_njangibenefit_cycle_alter_fine_fine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributioncycle',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('project', 'Project'), ('entertainment', 'Entertainment'), ('sinking_fund', 'Sinking Fund'), ('events', 'Events'), ('meetings', 'Meetings')], max_length=30, null=True),
        ),
    ]
