# Generated by Django 5.2.12 on 2026-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_communityfeature_feature_type'),
        ('finance', '0005_contributioncycle_feature_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialseason',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financialseason',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('project', 'Project'), ('entertainment', 'Entertainment'), ('sinking_fund', 'Sinking Fund'), ('events', 'Events'), ('meetings', 'Meetings')], max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='financialseason',
            unique_together={('community', 'feature_type', 'season_date')},
        ),
    ]
