# Generated by Django 5.2.12 on 2026-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_financialseason_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
