# Generated by Django 5.2.12 on 2026-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_loanapplication_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
    ]
