# Generated by Django 5.2.12 on 2026-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_communityfeature_feature_type'),
        ('finance', '0008_loan_repayment_frequency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contributioncycle',
            name='feature_type',
        ),
        migrations.AlterUniqueTogether(
            name='financialseason',
            unique_together={('community', 'season_date')},
        ),
        migrations.AddField(
            model_name='contribution',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('project', 'Project'), ('entertainment', 'Entertainment'), ('sinking_fund', 'Sinking Fund'), ('events', 'Events'), ('meetings', 'Meetings')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('membership', 'cycle', 'feature_type')},
        ),
        migrations.RemoveField(
            model_name='financialseason',
            name='feature_type',
        ),
    ]
