# Generated by Django 5.2.12 on 2026-04-01 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_contribution_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='njangibenefit',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='njangi_benefits', to='finance.contributioncycle'),
        ),
    ]
