# Generated by Django 5.2.12 on 2026-04-01 16:19

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_communityfeature_feature_type'),
        ('finance', '0011_alter_loan_status_loanpenalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('source_fund', models.CharField(choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('project', 'Project'), ('entertainment', 'Entertainment'), ('sinking_fund', 'Sinking Fund'), ('events', 'Events'), ('meetings', 'Meetings')], db_index=True, help_text='The fund/category from which money is spent.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenditure_date', models.DateField()),
                ('description', models.TextField(help_text='Mandatory justification for the expenditure.')),
                ('signature', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], db_index=True, default='posted', max_length=10)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='communities.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures_created', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='finance.financialseason')),
            ],
            options={
                'ordering': ['-expenditure_date', '-created'],
                'indexes': [models.Index(fields=['community', 'source_fund'], name='finance_exp_communi_c7e2e6_idx'), models.Index(fields=['community', 'expenditure_date'], name='finance_exp_communi_dd7cea_idx')],
            },
        ),
    ]
