# Generated by Django 5.2.12 on 2026-03-06 18:36

import django_extensions.db.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('community_type', models.CharField(choices=[('njangi', 'Njangi'), ('savings', 'Savings Group'), ('cooperative', 'Cooperative'), ('meeting', 'Meeting Group'), ('investment', 'Investment Group'), ('other', 'Other')], db_index=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('registration_fee_mode', models.CharField(choices=[('none', 'No Registration Fee'), ('fixed', 'Fixed Registration Fee')], default='none', max_length=20)),
                ('registration_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contribution_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('default_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('late_contribution_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('absence_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('minimum_membership_days_before_loan', models.PositiveIntegerField(default=30)),
                ('max_active_loans_per_member', models.PositiveIntegerField(default=1)),
                ('max_loan_multiple_of_savings', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=8)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('requires_guarantor', models.BooleanField(default=True)),
                ('minimum_guarantors', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('loan_officer', 'Loan Officer')], default='member', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('exited', 'Exited')], default='active', max_length=20)),
                ('joined_at', models.DateField()),
                ('exited_at', models.DateField(blank=True, null=True)),
                ('member_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('member_id_number', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('id_card_number', models.CharField(blank=True, max_length=100)),
                ('digital_signature', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('applied_role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('loan_officer', 'Loan Officer')], default='member', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('exited', 'Exited')], default='pending', max_length=20)),
                ('registration_fee_required', models.BooleanField(default=False)),
                ('registration_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
        ),
    ]
