# Generated by Django 5.2.12 on 2026-03-12 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypolicy',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='communities.community'),
        ),
        migrations.AddField(
            model_name='communityspace',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='System admin who created this community space.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_community_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityspace',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary owner assigned to this community space.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_community_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='community_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='communities.communityspace'),
        ),
        migrations.AddField(
            model_name='communityspacemembership',
            name='community_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.communityspace'),
        ),
        migrations.AddField(
            model_name='communityspacemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_space_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='communities.community'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='communities.membershipapplication'),
        ),
        migrations.AddIndex(
            model_name='communityspace',
            index=models.Index(fields=['slug'], name='communities_slug_db7d22_idx'),
        ),
        migrations.AddIndex(
            model_name='communityspace',
            index=models.Index(fields=['status'], name='communities_status_897e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_space', 'community_type'], name='communities_communi_54f24b_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['community_space', 'name'], name='communities_communi_931542_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('community_space', 'code'), ('community_space', 'name')},
        ),
        migrations.AddIndex(
            model_name='communityspacemembership',
            index=models.Index(fields=['community_space', 'role'], name='communities_communi_a25d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='communityspacemembership',
            index=models.Index(fields=['user', 'role'], name='communities_user_id_44ce79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communityspacemembership',
            unique_together={('community_space', 'user')},
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['community', 'status'], name='communities_communi_b8030b_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_3eba10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipapplication',
            unique_together={('community', 'user')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'status'], name='communities_communi_b7f99f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_ecd6aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('community', 'user')},
        ),
    ]
