# Generated by Django 5.2.12 on 2026-03-06 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitypolicy',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='communities.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.community'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='communities.community'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='communities.membershipapplication'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['community', 'status'], name='communities_communi_b8030b_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_3eba10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipapplication',
            unique_together={('community', 'user')},
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['community', 'status'], name='communities_communi_b7f99f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'status'], name='communities_user_id_ecd6aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('community', 'user')},
        ),
    ]
