# Generated by Django 5.2.12 on 2026-03-18 13:29

import apps.communities.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='document_back',
            field=models.ImageField(blank=True, help_text='Upload back side (required for ID card & driver license)', null=True, upload_to='membership_applications/documents/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.communities.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='document_front',
            field=models.ImageField(blank=True, help_text='Upload front side of the selected document', null=True, upload_to='membership_applications/documents/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.communities.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='document_type',
            field=models.CharField(choices=[('id_card', 'National ID'), ('passport', 'Passport'), ('driver_license', 'Driver License')], default='id_card', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Optional selfie for identity verification', null=True, upload_to='membership_applications/selfies/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.communities.models.validate_file_size]),
        ),
    ]
