# Generated by Django 5.2.12 on 2026-03-09 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, help_text='Community logo or identity image', null=True, upload_to='communities/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
