# Generated by Django 5.2.12 on 2026-03-20 07:16

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_membershipapplication_document_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeature',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('feature_type', models.CharField(choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('fines', 'Fines')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='communities.community')),
            ],
        ),
        migrations.CreateModel(
            name='MemberFeatureParticipation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communities.communityfeature')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_participations', to='communities.membership')),
            ],
        ),
        migrations.AddIndex(
            model_name='communityfeature',
            index=models.Index(fields=['community', 'feature_type'], name='communities_communi_ded157_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communityfeature',
            unique_together={('community', 'feature_type')},
        ),
        migrations.AddIndex(
            model_name='memberfeatureparticipation',
            index=models.Index(fields=['membership', 'feature'], name='communities_members_162cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='memberfeatureparticipation',
            index=models.Index(fields=['feature', 'is_active'], name='communities_feature_ec5f85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberfeatureparticipation',
            unique_together={('membership', 'feature')},
        ),
    ]
