# Generated by Django 5.2.12 on 2026-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_communityfeature_memberfeatureparticipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='applied_features',
            field=models.ManyToManyField(blank=True, related_name='membership_applications', to='communities.communityfeature'),
        ),
    ]
