# Generated by Django 5.2.12 on 2026-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_membershipapplication_applied_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfeature',
            name='feature_type',
            field=models.CharField(choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans')], max_length=30),
        ),
    ]
