# Generated by Django 5.2.12 on 2026-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communityfeature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityfeature',
            name='feature_type',
            field=models.CharField(choices=[('njangi', 'Njangi'), ('savings', 'Savings'), ('loans', 'Loans'), ('project', 'Project'), ('entertainment', 'Entertainment'), ('sinking_fund', 'Sinking Fund'), ('events', 'Events'), ('meetings', 'Meetings')], max_length=30),
        ),
    ]
