# Generated by Django 5.2.12 on 2026-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_communityfeature_feature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityspacemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('president', 'President'), ('manager', 'Manager'), ('viewer', 'Viewer'), ('chairperson', 'Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('loan_officer', 'Loan Officer')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('member', 'Member')], default='member', max_length=30),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='applied_role',
            field=models.CharField(choices=[('member', 'Member')], default='member', max_length=30),
        ),
    ]
