# Generated by Django 5.2.12 on 2026-03-06 18:36

import apps.users.managers
import apps.users.models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(blank=True, help_text='Full name of the user.', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, help_text='User is an admin.', verbose_name='is admin')),
                ('is_manually_deleted', models.BooleanField(default=False, help_text='Marks if the user was manually deleted.', verbose_name='is manually deleted')),
                ('has_accepted_terms', models.BooleanField(default=False, help_text='Indicates whether the user has accepted the Terms of Service and Privacy Policy during registration.', verbose_name='has accepted terms')),
                ('profile_picture', models.ImageField(blank=True, help_text="User's profile picture.", null=True, upload_to='profile/', verbose_name='Profile Picture')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('name', models.CharField(help_text='Name of the partner organization.', max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the partner.', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the partner organization.', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, help_text="Partner's logo image.", max_length=1000, null=True, upload_to=apps.users.models.partner_logo_path, verbose_name='Logo')),
                ('website', models.URLField(blank=True, help_text="Partner's website URL.", null=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the partner is actively displayed.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'indexes': [models.Index(fields=['slug'], name='users_partn_slug_f9c181_idx'), models.Index(fields=['is_deleted'], name='users_partn_is_dele_2bb370_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('region', models.CharField(blank=True, default='Cameroon', max_length=50, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, default='00000', max_length=20, verbose_name='Zip Code')),
                ('user', models.OneToOneField(help_text='Associated user account.', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
