# Generated by Django 5.2.12 on 2026-03-12 14:05

import django_extensions.db.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProfile',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('current_score', models.PositiveIntegerField(db_index=True, default=0)),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('creditworthiness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], default='fair', max_length=20)),
                ('recommended_max_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('probability_of_default', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('scoring_version', models.CharField(default='v1', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('score', models.PositiveIntegerField()),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('creditworthiness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20)),
                ('probability_of_default', models.DecimalField(decimal_places=4, max_digits=6)),
                ('recommended_max_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('scoring_version', models.CharField(default='v1', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRiskAssessment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('score_used', models.PositiveIntegerField()),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('creditworthiness', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20)),
                ('probability_of_default', models.DecimalField(decimal_places=4, max_digits=6)),
                ('recommended_max_loan_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recommended_term_months', models.PositiveIntegerField(default=0)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('recommendation', models.CharField(blank=True, max_length=100)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberBehaviorSnapshot',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier for the record.', primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('contribution_consistency', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('repayment_punctuality', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('attendance_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('savings_stability', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('fine_frequency', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('default_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('debt_ratio', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
            ],
        ),
    ]
