# Generated by Django 5.2.12 on 2026-03-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditprofile',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_profile', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.membership'),
        ),
    ]
