# Generated by Django 5.2.12 on 2026-03-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('communities', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscorehistory',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financialseason'),
        ),
        migrations.AddField(
            model_name='loanriskassessment',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='finance.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanriskassessment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='memberbehaviorsnapshot',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_snapshots', to='communities.membership'),
        ),
        migrations.AddField(
            model_name='memberbehaviorsnapshot',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_snapshots', to='finance.financialseason'),
        ),
        migrations.AlterUniqueTogether(
            name='memberbehaviorsnapshot',
            unique_together={('membership', 'season')},
        ),
    ]
