# Generated by Django 5.2.12 on 2026-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditprofile',
            name='explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
