# Generated by Django 5.2.12 on 2026-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='meetings/recordings/'),
        ),
        migrations.AddField(
            model_name='meetingminute',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingminute',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meetingminute',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
